site_name: Mkdocs Prueba01
theme:
  name: material
  palette: 
    - media: "(prefers-color-scheme: light)"    
    # Palette toggle for light mode
      scheme: default
      primary: blue
      accent: green 
      toggle:
        icon: material/toggle-switch-off-outline
        name: Cambiar a modo oscuro

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Cambiar a modo claro
  language: es
  features:
    #- navigation.sections
    - navigation.top
    #- navigation.expand
    - toc.integrate
    - search.highlight
    - content.code.annotation
    - content.code.copy

markdown_extensions:
  - meta
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - attr_list
  - md_in_html
  - footnotes
  
plugins: 
  - search:
      lang: es


extra_css:
  - stylesheets/extra.css

extra:
  analytics: 
      provider: google 
      property: G-3NX5MD5C8H

  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/jmunozji
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ppmunozj